### ISSUE TITLE
rust-999 requires more than 10 GB of space to compile

### ISSUE THREAD

**Issue by suhr** [gentoo/gentoo-rust#231]
This is complete madness. What could actually go so wrong?

**Comment by Slabity** [comment]
This is probably due to how the rustbuild system works. It bootstraps a rustc+cargo+stdlib set in order to build a second rustc+cargo+stdlib set. The second set is then used to compile the tools that will be installed. It's not pretty.

I believe we can avoid this with the `--enable-local-rust` configure flag, but that requires rustc and cargo to already be installed.

**Comment by suhr** [comment]
Looks like most of that size is static compiled llvm. But not so long ago `rust-9999` didn't require 10 GB of space.

**Comment by mpkh** [comment]
obsolete
